stages:
  preprocess:
    cmd: python preprocess.py data/mushrooms.csv data/preprocessed_dataset.csv
    outs:
      - data/preprocessed_dataset.csv
  train:
    cmd: python train.py data/preprocessed_dataset.csv model.pkl
    outs:
      - best_model.pkl
    deps:
      - data/preprocessed_dataset.csv
  evaluate:
    cmd: python evaluate.py best_model.pkl data/preprocessed_dataset.csv
    outs:
      - evaluation.txt
    deps:
      - best_model.pkl
      - data/preprocessed_dataset.csv
  feature_importance:
    cmd: python feature_importance.py best_model.pkl data/preprocessed_dataset.csv feature_importance.png
    outs:
      - feature_importance.png
    deps:
      - best_model.pkl
      - data/preprocessed_dataset.csv