name: Docker Image CI

on:
  push:
    branches: [ 'main','docker' ]
    paths:
      - "HW1/**"
  pull_request:
    branches: [ 'main','docker' ]
    paths:
      - "HW1/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image 
        uses: docker/build-push-action@v4
        with:
          tags: mikloskosarszky/docker_miki:starspace
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./HW1
          file: HW1/Dockerfile
          push: true
