name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mikloskosarszky }}
          password: ${{ secrets.dckr_pat_RdLQEYYSw64NNVC_CNt2f84z8KQ }}
        
      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mikloskosarszky/docker_miki
          registry: docker.io
          username: ${{ secrets.mikloskosarszky }}
          password: ${{ secrets.docker_miki }}
        
