name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    paths:
      - "HW1/**"
  pull_request:
    branches: [ "*" ]
    paths:
      - "HW1/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
        
      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mikloskosarszky/docker_miki
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./HW1
          file: HW1/Dockerfile
          push: true
